/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarterKitRouteImport } from './routes/starter-kit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ProgressIndexRouteImport } from './routes/progress.index'
import { Route as DiaryIndexRouteImport } from './routes/diary.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ProgressSlugRouteImport } from './routes/progress.$slug'
import { Route as FreebiesSlugRouteImport } from './routes/freebies.$slug'
import { Route as DiarySlugRouteImport } from './routes/diary.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const StarterKitRoute = StarterKitRouteImport.update({
  id: '/starter-kit',
  path: '/starter-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgressRoute,
} as any)
const DiaryIndexRoute = DiaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiaryRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ProgressSlugRoute = ProgressSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgressRoute,
} as any)
const FreebiesSlugRoute = FreebiesSlugRouteImport.update({
  id: '/freebies/$slug',
  path: '/freebies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarySlugRoute = DiarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiaryRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/diary': typeof DiaryRouteWithChildren
  '/progress': typeof ProgressRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter-kit': typeof StarterKitRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diary/$slug': typeof DiarySlugRoute
  '/freebies/$slug': typeof FreebiesSlugRoute
  '/progress/$slug': typeof ProgressSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/diary/': typeof DiaryIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter-kit': typeof StarterKitRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diary/$slug': typeof DiarySlugRoute
  '/freebies/$slug': typeof FreebiesSlugRoute
  '/progress/$slug': typeof ProgressSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog': typeof BlogIndexRoute
  '/diary': typeof DiaryIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/diary': typeof DiaryRouteWithChildren
  '/progress': typeof ProgressRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter-kit': typeof StarterKitRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diary/$slug': typeof DiarySlugRoute
  '/freebies/$slug': typeof FreebiesSlugRoute
  '/progress/$slug': typeof ProgressSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/diary/': typeof DiaryIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/diary'
    | '/progress'
    | '/resources'
    | '/shop'
    | '/sitemap.xml'
    | '/starter-kit'
    | '/blog/$slug'
    | '/diary/$slug'
    | '/freebies/$slug'
    | '/progress/$slug'
    | '/resources/$slug'
    | '/shop/$slug'
    | '/blog/'
    | '/diary/'
    | '/progress/'
    | '/resources/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/starter-kit'
    | '/blog/$slug'
    | '/diary/$slug'
    | '/freebies/$slug'
    | '/progress/$slug'
    | '/resources/$slug'
    | '/shop/$slug'
    | '/blog'
    | '/diary'
    | '/progress'
    | '/resources'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/diary'
    | '/progress'
    | '/resources'
    | '/shop'
    | '/sitemap.xml'
    | '/starter-kit'
    | '/blog/$slug'
    | '/diary/$slug'
    | '/freebies/$slug'
    | '/progress/$slug'
    | '/resources/$slug'
    | '/shop/$slug'
    | '/blog/'
    | '/diary/'
    | '/progress/'
    | '/resources/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  DiaryRoute: typeof DiaryRouteWithChildren
  ProgressRoute: typeof ProgressRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StarterKitRoute: typeof StarterKitRoute
  FreebiesSlugRoute: typeof FreebiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starter-kit': {
      id: '/starter-kit'
      path: '/starter-kit'
      fullPath: '/starter-kit'
      preLoaderRoute: typeof StarterKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/progress/': {
      id: '/progress/'
      path: '/'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof ProgressRoute
    }
    '/diary/': {
      id: '/diary/'
      path: '/'
      fullPath: '/diary/'
      preLoaderRoute: typeof DiaryIndexRouteImport
      parentRoute: typeof DiaryRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/progress/$slug': {
      id: '/progress/$slug'
      path: '/$slug'
      fullPath: '/progress/$slug'
      preLoaderRoute: typeof ProgressSlugRouteImport
      parentRoute: typeof ProgressRoute
    }
    '/freebies/$slug': {
      id: '/freebies/$slug'
      path: '/freebies/$slug'
      fullPath: '/freebies/$slug'
      preLoaderRoute: typeof FreebiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/$slug': {
      id: '/diary/$slug'
      path: '/$slug'
      fullPath: '/diary/$slug'
      preLoaderRoute: typeof DiarySlugRouteImport
      parentRoute: typeof DiaryRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DiaryRouteChildren {
  DiarySlugRoute: typeof DiarySlugRoute
  DiaryIndexRoute: typeof DiaryIndexRoute
}

const DiaryRouteChildren: DiaryRouteChildren = {
  DiarySlugRoute: DiarySlugRoute,
  DiaryIndexRoute: DiaryIndexRoute,
}

const DiaryRouteWithChildren = DiaryRoute._addFileChildren(DiaryRouteChildren)

interface ProgressRouteChildren {
  ProgressSlugRoute: typeof ProgressSlugRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
}

const ProgressRouteChildren: ProgressRouteChildren = {
  ProgressSlugRoute: ProgressSlugRoute,
  ProgressIndexRoute: ProgressIndexRoute,
}

const ProgressRouteWithChildren = ProgressRoute._addFileChildren(
  ProgressRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  DiaryRoute: DiaryRouteWithChildren,
  ProgressRoute: ProgressRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StarterKitRoute: StarterKitRoute,
  FreebiesSlugRoute: FreebiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
