/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ProgressIndexRouteImport } from './routes/progress.index'
import { Route as DiaryIndexRouteImport } from './routes/diary.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ProgressSlugRouteImport } from './routes/progress.$slug'
import { Route as DiarySlugRouteImport } from './routes/diary.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryIndexRoute = DiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressSlugRoute = ProgressSlugRouteImport.update({
  id: '/progress/$slug',
  path: '/progress/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarySlugRoute = DiarySlugRouteImport.update({
  id: '/diary/$slug',
  path: '/diary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diary/$slug': typeof DiarySlugRoute
  '/progress/$slug': typeof ProgressSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/diary/': typeof DiaryIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diary/$slug': typeof DiarySlugRoute
  '/progress/$slug': typeof ProgressSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog': typeof BlogIndexRoute
  '/diary': typeof DiaryIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diary/$slug': typeof DiarySlugRoute
  '/progress/$slug': typeof ProgressSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/diary/': typeof DiaryIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/diary/$slug'
    | '/progress/$slug'
    | '/resources/$slug'
    | '/shop/$slug'
    | '/blog/'
    | '/diary/'
    | '/progress/'
    | '/resources/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/diary/$slug'
    | '/progress/$slug'
    | '/resources/$slug'
    | '/shop/$slug'
    | '/blog'
    | '/diary'
    | '/progress'
    | '/resources'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/diary/$slug'
    | '/progress/$slug'
    | '/resources/$slug'
    | '/shop/$slug'
    | '/blog/'
    | '/diary/'
    | '/progress/'
    | '/resources/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DiarySlugRoute: typeof DiarySlugRoute
  ProgressSlugRoute: typeof ProgressSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DiaryIndexRoute: typeof DiaryIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/': {
      id: '/diary/'
      path: '/diary'
      fullPath: '/diary/'
      preLoaderRoute: typeof DiaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/$slug': {
      id: '/progress/$slug'
      path: '/progress/$slug'
      fullPath: '/progress/$slug'
      preLoaderRoute: typeof ProgressSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/$slug': {
      id: '/diary/$slug'
      path: '/diary/$slug'
      fullPath: '/diary/$slug'
      preLoaderRoute: typeof DiarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  DiarySlugRoute: DiarySlugRoute,
  ProgressSlugRoute: ProgressSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DiaryIndexRoute: DiaryIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
